AWSTemplateFormatVersion: "2010-09-09"
Description: A sample template
Resources:
  DummyVPC:
    Type: AWS::EC2::VPC
    Properties:
      CidrBlock: 10.0.0.0/16
      EnableDnsSupport: 'true'
      EnableDnsHostnames: 'true'
      Tags:
       - Key: Name
         Value: Dummy-VPC

  DummyInternetGateway:
    Type: AWS::EC2::InternetGateway
    Properties:
      Tags:
      - Key: Name
        Value: Dummy-IGW

  DummyAttachGateway:
    Type: AWS::EC2::VPCGatewayAttachment
    Properties:
      VpcId:
         Ref: DummyVPC
      InternetGatewayId:
         Ref: DummyInternetGateway

  DummyPUBSubnet:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId:
        Ref: DummyVPC
      CidrBlock: 10.0.0.0/20
      AvailabilityZone: "us-east-1a"
      MapPublicIpOnLaunch: "true"
      Tags:
      - Key: Name
        Value: Dummy-pub-sub

  DummyPVTSubnet:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId:
        Ref: DummyVPC
      CidrBlock: 10.0.16.1/20
      AvailabilityZone: "us-east-1b"
      Tags:
      - Key: Name
        Value: Dummy-pvt-sub

  DummyPUBRouteTable:
    Type: AWS::EC2::RouteTable
    Properties:
      VpcId:  
        Ref: DummyVPC
      Tags:
      - Key: Name
        Value: Dummy-pub-RT

  DummyPVTRouteTable:
    Type: AWS::EC2::RouteTable
    Properties:
      VpcId:  
        Ref: DummyVPC
      Tags:
      - Key: Name
        Value: Dummy-pvt-RT

  DummyPUBSubnetRouteTableAssociation:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      SubnetId:
        Ref: DummyPUBSubnet
      RouteTableId:
        Ref: DummyPUBRouteTable

  DummySubnetRouteTableAssociation:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      SubnetId:
        Ref: DummyPVTSubnet
      RouteTableId:
        Ref: DummyPVTRouteTable

  DummyADDRoute:
    Type: AWS::EC2::Route
    DependsOn: DummyAttachGateway
    Properties:
       RouteTableId:
         Ref: DummyPUBRouteTable
       DestinationCidrBlock: 0.0.0.0/0
       GatewayId:
         Ref: DummyInternetGateway
